name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run backend tests
      run: |
        cd backend
        npm test

    - name: Run backend coverage
      run: |
        cd backend
        npm run coverage
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend
